import BigNumber from 'bignumber.js';

var SPLib = {
    low0_0: {
        id: 'l0_0',
        top: false,
        rank: 'Apprentice',
        desc: 'Gain 10 PowerLevel per second.',
        require: new BigNumber(500),
        number: new BigNumber(1),
        getPrev: () => { return null },
        getNext: () => { return SPLib.low0_1 },
    },
    low0_1: {
        id: 'l0_1',
        top: false,
        rank: 'Journeyman',
        desc: 'Gain 30 PowerLevel per second.',
        require: new BigNumber(200),
        getPrev: () => { return SPLib.low0_0 },
        getNext: () => { return SPLib.low0_2 },
    },
    low0_2: {
        id: 'l0_2',
        top: false,
        rank: 'Expert',
        desc: 'Gain 50 PowerLevel per second.',
        require: new BigNumber(10).pow(4).times(4),
        getPrev: () => { return SPLib.low0_1 },
        getNext: () => { return SPLib.low0_3 },
    },
    low0_3: {
        id: 'l0_3',
        top: false,
        rank: 'Artisan',
        desc: 'Gain 200 PowerLevel per second.',
        require: new BigNumber(10).pow(5).times(7),
        getPrev: () => { return SPLib.low0_2 },
        getNext: () => { return SPLib.low0_4 },
    },
    low0_4: {
        id: 'l0_4',
        top: false,
        rank: 'Master',
        desc: 'Gain 2,020 PowerLevel per second.',
        require: new BigNumber(10).pow(7).times(2),
        getPrev: () => { return SPLib.low0_3},
        getNext: () => { return SPLib.low0_5 },
    },
    low0_5: {
        id: 'l0_5',
        top: false,
        rank: 'Grand Master',
        desc: 'Gain 10,080 PowerLevel per second.',
        require: new BigNumber(10).pow(9).times(3),
        getPrev: () => { return SPLib.low0_4 },
        getNext: () => { return SPLib.low0_6 },
    },
    low0_6: {
        id: 'l0_6',
        top: false,
        rank: 'Zen Master',
        desc: 'Gain 3,100,003 PowerLevel per second.',
        require: new BigNumber(10).pow(11),
        getPrev: () => { return SPLib.low0_5 },
        getNext: () => { return SPLib.low0_7 },
    },
    low0_7: {
        id: 'l0_7',
        top: false,
        rank: 'Creator',
        desc: 'Gain 50,090,060 PowerLevel per second.',
        require: new BigNumber(10).pow(12),
        getPrev: () => { return SPLib.low0_6 },
        getNext: () => { return SPLib.low0_8 },
    },
    low0_8: {
        id: 'l0_0',
        top: false,
        rank: 'Omni',
        desc: 'Gain 109,090,090 PowerLevel per second.',
        require: new BigNumber(10).pow(16),
        getPrev: () => { return SPLib.low0_7 },
        getNext: () => { null },
    },
    mid0_0: {
        id: 'm0_0',
        top: false,
        rank: 'Apprentice',
        desc: 'Gain 10 PowerLevel per second.',
        require: new BigNumber(1000),
        number: new BigNumber(1),
        getPrev: () => { return null },
        getNext: () => { return SPLib.mid0_1 },
    },
    mid0_1: {
        id: 'm0_1',
        top: false,
        rank: 'Journeyman',
        desc: 'Gain 30 PowerLevel per second.',
        require: new BigNumber(5000),
        getPrev: () => { return SPLib.mid0_0 },
        getNext: () => { return SPLib.mid0_2 },
    },
    mid0_2: {
        id: 'm0_2',
        top: false,
        rank: 'Expert',
        desc: 'Gain 50 PowerLevel per second.',
        require: new BigNumber(10).pow(5),
        getPrev: () => { return SPLib.mid0_1 },
        getNext: () => { return SPLib.mid0_3 },
    },
    mid0_3: {
        id: 'm0_3',
        top: false,
        rank: 'Artisan',
        desc: 'Gain 100 PowerLevel per second.',
        require: new BigNumber(10).pow(6).times(3),
        getPrev: () => { return SPLib.mid0_2 },
        getNext: () => { return SPLib.mid0_4 },
    },
    mid0_4: {
        id: 'm0_4',
        top: false,
        rank: 'Master',
        desc: 'Gain 1000 PowerLevel per second.',
        require: new BigNumber(10).pow(8).times(4),
        getPrev: () => { return SPLib.mid0_3},
        getNext: () => { return SPLib.mid0_5 },
    },
    mid0_5: {
        id: 'm0_5',
        top: false,
        rank: 'Grand Master',
        desc: 'Gain 10,080 PowerLevel per second.',
        require: new BigNumber(10).pow(10).times(5),
        getPrev: () => { return SPLib.mid0_4 },
        getNext: () => { return SPLib.mid0_6 },
    },
    mid0_6: {
        id: 'm0_6',
        top: false,
        rank: 'Zen Master',
        desc: 'Gain 20,100,10 PowerLevel per second.',
        require: new BigNumber(10).pow(11),
        getPrev: () => { return SPLib.mid0_5 },
        getNext: () => { return SPLib.mid0_7 },
    },
    mid0_7: {
        id: 'm0_7',
        top: false,
        rank: 'Creator',
        desc: 'Gain 3,090,060 PowerLevel per second.',
        require: new BigNumber(10).pow(13),
        getPrev: () => { return SPLib.mid0_6 },
        getNext: () => { return SPLib.mid0_8 },
    },
    mid0_8: {
        id: 'm0_0',
        top: false,
        rank: 'Omni',
        desc: 'Gain 96,669,090,090 PowerLevel per second.',
        require: new BigNumber(10).pow(16),
        getPrev: () => { return SPLib.mid0_7 },
        getNext: () => { null },
    },
    
    

}

const getRandomPower = (){

}

export { getRandomPower };